.TH "addsouvenir" 3 "Mon May 16 2016" "Version 1.0" "Baseball Fantasy Vacation Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
addsouvenir \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <addsouvenir\&.h>\fP
.PP
Inherits QDialog\&.
.SS "Signals"

.in +1c
.ti -1c
.RI "void \fBrefreshModels\fP ()"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBaddsouvenir\fP (QWidget *parent=0, \fBDatabase\fP *db=0, QString stadiumName='null')"
.br
.ti -1c
.RI "\fB~addsouvenir\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 11 of file addsouvenir\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "addsouvenir::addsouvenir (QWidget * parent = \fC0\fP, \fBDatabase\fP * db = \fC0\fP, QString stadiumName = \fC'null'\fP)\fC [explicit]\fP"

.PP
Definition at line 4 of file addsouvenir\&.cpp\&.
.SS "addsouvenir::~addsouvenir ()"

.PP
Definition at line 14 of file addsouvenir\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void addsouvenir::refreshModels ()\fC [signal]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Baseball Fantasy Vacation Documentation from the source code\&.
