.TH "AdminLogin" 3 "Mon May 16 2016" "Version 1.0" "Baseball Fantasy Vacation Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AdminLogin \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <adminlogin\&.h>\fP
.PP
Inherits QDialog\&.
.SS "Signals"

.in +1c
.ti -1c
.RI "void \fBadminStatusChanged\fP (bool status)"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAdminLogin\fP (QWidget *parent=0)"
.br
.ti -1c
.RI "\fB~AdminLogin\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 13 of file adminlogin\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "AdminLogin::AdminLogin (QWidget * parent = \fC0\fP)\fC [explicit]\fP"

.PP
Definition at line 4 of file adminlogin\&.cpp\&.
.SS "AdminLogin::~AdminLogin ()"

.PP
Definition at line 13 of file adminlogin\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void AdminLogin::adminStatusChanged (bool status)\fC [signal]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Baseball Fantasy Vacation Documentation from the source code\&.
