.TH "comp" 3 "Mon May 16 2016" "Version 1.0" "Baseball Fantasy Vacation Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
comp \- The comp struct Comparator struct used for comparing the weights of two edges\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <vertex\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBoperator()\fP (const \fBEdge\fP &e1, const \fBEdge\fP &e2) const "
.br
.in -1c
.SH "Detailed Description"
.PP 
The comp struct Comparator struct used for comparing the weights of two edges\&. 
.PP
Definition at line 20 of file vertex\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "bool comp::operator() (const \fBEdge\fP & e1, const \fBEdge\fP & e2) const\fC [inline]\fP"

.PP
Definition at line 22 of file vertex\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Baseball Fantasy Vacation Documentation from the source code\&.
