.TH "src/header/database.h" 3 "Mon May 16 2016" "Version 1.0" "Baseball Fantasy Vacation Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/header/database.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <QtSql>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDatabase\fP"
.br
.RI "\fIThe \fBDatabase\fP class is a wrapper for QSqlDatabase\&. \fP"
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBDEBUG\fP   0"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define DEBUG   0"

.PP
Definition at line 5 of file database\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Baseball Fantasy Vacation Documentation from the source code\&.
