.TH "Edge" 3 "Mon May 16 2016" "Version 1.0" "Baseball Fantasy Vacation Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Edge \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <vertex\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBidFrom\fP"
.br
.ti -1c
.RI "int \fBidTo\fP"
.br
.ti -1c
.RI "int \fBweight\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 9 of file vertex\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "int Edge::idFrom"

.PP
Definition at line 11 of file vertex\&.h\&.
.SS "int Edge::idTo"

.PP
Definition at line 12 of file vertex\&.h\&.
.SS "int Edge::weight"

.PP
Definition at line 13 of file vertex\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Baseball Fantasy Vacation Documentation from the source code\&.
