.TH "EditStadiumInfo" 3 "Mon May 16 2016" "Version 1.0" "Baseball Fantasy Vacation Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EditStadiumInfo \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <editstadiuminfo\&.h>\fP
.PP
Inherits QWidget\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEditStadiumInfo\fP (QWidget *parent=0)"
.br
.ti -1c
.RI "\fB~EditStadiumInfo\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 10 of file editstadiuminfo\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "EditStadiumInfo::EditStadiumInfo (QWidget * parent = \fC0\fP)\fC [explicit]\fP"

.PP
Definition at line 4 of file editstadiuminfo\&.cpp\&.
.SS "EditStadiumInfo::~EditStadiumInfo ()"

.PP
Definition at line 11 of file editstadiuminfo\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Baseball Fantasy Vacation Documentation from the source code\&.
