.TH "src/header/graph.h" 3 "Mon May 16 2016" "Version 1.0" "Baseball Fantasy Vacation Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/header/graph.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <QString>\fP
.br
\fC#include <QList>\fP
.br
\fC#include 'database\&.h'\fP
.br
\fC#include 'Heap\&.h'\fP
.br
\fC#include 'vertex\&.h'\fP
.br
\fC#include 'vertexqueue\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBGraph\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBDEBUG\fP   0"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define DEBUG   0"

.PP
Definition at line 4 of file graph\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Baseball Fantasy Vacation Documentation from the source code\&.
