.TH "HomePage" 3 "Mon May 16 2016" "Version 1.0" "Baseball Fantasy Vacation Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HomePage \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <homepage\&.h>\fP
.PP
Inherits QWidget\&.
.SS "Signals"

.in +1c
.ti -1c
.RI "void \fBisFinished\fP (bool)"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHomePage\fP (QWidget *parent=0)"
.br
.ti -1c
.RI "\fB~HomePage\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 10 of file homepage\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "HomePage::HomePage (QWidget * parent = \fC0\fP)\fC [explicit]\fP"

.PP
Definition at line 7 of file homepage\&.cpp\&.
.SS "HomePage::~HomePage ()"

.PP
Definition at line 24 of file homepage\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void HomePage::isFinished (bool)\fC [signal]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Baseball Fantasy Vacation Documentation from the source code\&.
