.TH "IndexOutOfBounds" 3 "Mon May 16 2016" "Version 1.0" "Baseball Fantasy Vacation Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IndexOutOfBounds \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Exceptions\&.h>\fP
.PP
Inherits \fBRuntimeException\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBIndexOutOfBounds\fP (const std::string &err)"
.br
.RI "\fICreate an \fBIndexOutOfBounds\fP exception with a custom error message\&. \fP"
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
An exception class for \fBIndexOutOfBounds\fP errors 
.PP
\fBAuthor:\fP
.RS 4
Jesse Mazzella 
.RE
.PP

.PP
Definition at line 45 of file Exceptions\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "IndexOutOfBounds::IndexOutOfBounds (const std::string & err)\fC [inline]\fP"

.PP
Create an \fBIndexOutOfBounds\fP exception with a custom error message\&. 
.PP
Definition at line 50 of file Exceptions\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Baseball Fantasy Vacation Documentation from the source code\&.
