.TH "src/header/mainwindow.h" 3 "Mon May 16 2016" "Version 1.0" "Baseball Fantasy Vacation Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/header/mainwindow.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <QMainWindow>\fP
.br
\fC#include <QMap>\fP
.br
\fC#include <QString>\fP
.br
\fC#include <QStack>\fP
.br
\fC#include <QFile>\fP
.br
\fC#include <QMessageBox>\fP
.br
\fC#include <QtGui>\fP
.br
\fC#include '\&.\&./header/adminlogin\&.h'\fP
.br
\fC#include '\&.\&./header/stadiumdetails\&.h'\fP
.br
\fC#include '\&.\&./header/homepage\&.h'\fP
.br
\fC#include '\&.\&./header/editstadiuminfo\&.h'\fP
.br
\fC#include '\&.\&./header/plantrip\&.h'\fP
.br
\fC#include '\&.\&./header/purchasewindow\&.h'\fP
.br
\fC#include '\&.\&./header/tripsummary\&.h'\fP
.br
\fC#include '\&.\&./header/database\&.h'\fP
.br
\fC#include '\&.\&./header/stadiumtablemodel\&.h'\fP
.br
\fC#include '\&.\&./header/souvenirtablemodel\&.h'\fP
.br
\fC#include <QDebug>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMainWindow\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBUi\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBpages\fP { \fBPAGE_MAIN\fP, \fBPAGE_SPLASH\fP, \fBPAGE_HOME\fP, \fBPAGE_PLAN_TRIP\fP, \fBPAGE_STADIUM_DETAILS\fP, \fBPAGE_PURCHASE_WINDOW\fP, \fBPAGE_EDIT_STADIUM_INFO\fP, \fBPAGE_TRIP_SUMMARY\fP }"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBpages\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIPAGE_MAIN \fP\fP
.TP
\fB\fIPAGE_SPLASH \fP\fP
.TP
\fB\fIPAGE_HOME \fP\fP
.TP
\fB\fIPAGE_PLAN_TRIP \fP\fP
.TP
\fB\fIPAGE_STADIUM_DETAILS \fP\fP
.TP
\fB\fIPAGE_PURCHASE_WINDOW \fP\fP
.TP
\fB\fIPAGE_EDIT_STADIUM_INFO \fP\fP
.TP
\fB\fIPAGE_TRIP_SUMMARY \fP\fP
.PP
Definition at line 27 of file mainwindow\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Baseball Fantasy Vacation Documentation from the source code\&.
