.TH "md_docs_design" 3 "Mon May 16 2016" "Version 1.0" "Baseball Fantasy Vacation Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_docs_design \- Application Design Specs 
Document to store the specifications and design of the application
.PP
\fCmainwindow\fP
.IP "\(bu" 2
\fBWidth\fP: 700
.IP "\(bu" 2
\fBHeight\fP: 500
.PP
.PP
\fCmainwindow_mainWidget\fP : The mainwindow widget that contains everything
.IP "\(bu" 2
\fBWidth\fP: 700
.IP "\(bu" 2
\fBHeight\fP: 444
.PP
.PP
\fCmainwindow_stackedWidget\fP : The mainwindow stacked widget that contains each form and ui view for the application
.IP "\(bu" 2
\fBWidth\fP: 680
.IP "\(bu" 2
\fBHeight\fP: 360
.PP
.PP
\fCmainwindow_horizontalSpacer_buttons\fP : Spacer that goes between the mainwindow buttons
.IP "\(bu" 2
\fBsize type\fP: preferred
.IP "\(bu" 2
\fBWidth\fP: 40
.IP "\(bu" 2
\fBHeight\fP: 20 
.PP

