.TH "md_docs_stadium-distances" 3 "Mon May 16 2016" "Version 1.0" "Baseball Fantasy Vacation Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_docs_stadium-distances \- stadium-distances 
Stadium Index | Stadium Name | Distance :------------:|:-------------- |----------- 1 | Angels Stadium of Anaheim |
.IP "\(bu" 2
| Petco Park | 110
.IP "\(bu" 2
| Target Field | 1500
.IP "\(bu" 2
| AT&T PARK | 340
.IP "\(bu" 2
| O\&.co Stadium | 340
.IP "\(bu" 2
| Dodger Stadium | 0
.PP
.PP
2 | Comerica Park |
.IP "\(bu" 2
| Rogers Stadium | 210
.IP "\(bu" 2
| Progressive Field | 90
.IP "\(bu" 2
| US Cellular Field | 240
.IP "\(bu" 2
| Wrigley Field | 240
.PP
.PP
3 | Fenway Park |
.IP "\(bu" 2
| Rogers Center | 430
.IP "\(bu" 2
| Yankee Stadium | 195
.IP "\(bu" 2
| Citi Stadium | 195
.IP "\(bu" 2
| Marlins Park | 1255
.PP
.PP
4 | Globe Life Park |
.IP "\(bu" 2
| Coors Field | 650
.IP "\(bu" 2
| Chase Field | 870
.IP "\(bu" 2
| Turner Field | 740
.IP "\(bu" 2
| Minute Maid Park | 230
.IP "\(bu" 2
| Kauffman Stadium | 460
.PP
.PP
5 | Kauffman Stadium |
.IP "\(bu" 2
| Coors Field | 560
.IP "\(bu" 2
| Wrigley Field | 415
.IP "\(bu" 2
| US Cellular Field | 415
.IP "\(bu" 2
| Busch Stadium | 235
.IP "\(bu" 2
| Globe Life Park | 460
.PP
.PP
6 | Minute Maid Park |
.IP "\(bu" 2
| Chase Field | 1115
.IP "\(bu" 2
| Tropicano Field | 790
.IP "\(bu" 2
| Marlins Park | 965
.IP "\(bu" 2
| Globe Life Park | 230
.PP
.PP
7 | O\&.co Coliseum (Oakland) |
.IP "\(bu" 2
| AT&T Park | 0
.IP "\(bu" 2
| Safeco Field | 680
.IP "\(bu" 2
| Chase Field | 650
.IP "\(bu" 2
| Dodger Stadium | 340
.IP "\(bu" 2
| Angels Stadium | 340
.PP
.PP
8 | Oriole Park at Camden Yards |
.IP "\(bu" 2
| Nationals Park | 0
.IP "\(bu" 2
| Citizens Bank Park | 90
.IP "\(bu" 2
| PNC Park | 195
.IP "\(bu" 2
| Turner Field | 560
.IP "\(bu" 2
| Marlins Park | 930
.PP
.PP
9 | Progressive Field |
.IP "\(bu" 2
| Comerica Park | 90
.IP "\(bu" 2
| Great American Ballpark | 225
.IP "\(bu" 2
| PNC Park | 115
.PP
.PP
10| Rogers Center |
.IP "\(bu" 2
| Fenway Park | 430
.IP "\(bu" 2
| Safeco Field | 2070
.IP "\(bu" 2
| Miller Park | 430
.IP "\(bu" 2
| Comerica Park | 210
.IP "\(bu" 2
| PNC Park | 225
.PP
.PP
11| SafeCo Field |
.IP "\(bu" 2
| AT&T Park | 680
.IP "\(bu" 2
| Rogers Center | 2070
.IP "\(bu" 2
| Target Field | 1390
.PP
.PP
12| Target Field |
.IP "\(bu" 2
| SafeCo Field | 1390
.IP "\(bu" 2
| Dodger Stadium | 1500
.IP "\(bu" 2
| Angel Stadium | 1500
.IP "\(bu" 2
| Busch Stadium | 465
.IP "\(bu" 2
| Miller Park | 300
.PP
.PP
13| Tropicana Field |
.IP "\(bu" 2
| Great American Ballpark | 790
.IP "\(bu" 2
| Minute Maid Park | 790
.IP "\(bu" 2
| Marlins Park | 210
.PP
.PP
14| US Cellular Field |
.IP "\(bu" 2
| Wrigley Field | 0
.IP "\(bu" 2
| Miller Park | 80
.IP "\(bu" 2
| Comerica Park | 240
.IP "\(bu" 2
| Great American Ballpark | 250
.IP "\(bu" 2
| Kauffman Stadium | 415
.PP
.PP
15| Yankee Stadium |
.IP "\(bu" 2
| Fenway Park | 195
.IP "\(bu" 2
| Citi Field | 0
.IP "\(bu" 2
| Citizens Bank Park | 80
.IP "\(bu" 2
| PNC Park | 315
.PP
.PP
16| AT&T Park |
.IP "\(bu" 2
| SafeCo Field | 680
.IP "\(bu" 2
| O\&.co Coliseum (Oakland) | 0
.IP "\(bu" 2
| Dodger Stadium | 340
.IP "\(bu" 2
| Angels Stadium | 340
.IP "\(bu" 2
| Chase Field | 650
.PP
.PP
17| Busch Stadium |
.IP "\(bu" 2
| Minute Maid Park | 680
.IP "\(bu" 2
| Kauffman Stadium | 235
.IP "\(bu" 2
| Great American Ballpark | 310
.IP "\(bu" 2
| Target Field | 465
.PP
.PP
18| Chase Field |
.IP "\(bu" 2
| AT&T Park | 650
.IP "\(bu" 2
| O\&.co Coliseum (Oakland) | 650
.IP "\(bu" 2
| PETCO Park | 300
.IP "\(bu" 2
| Coors Field | 580
.IP "\(bu" 2
| Rangers Ballpark | 870
.IP "\(bu" 2
| Minute Maid Park | 1115
.PP
.PP
19| Citi Field |
.IP "\(bu" 2
| Yankee Stadium | 0
.IP "\(bu" 2
| Citizens Bank Park | 80
.IP "\(bu" 2
| Fenway Park | 195
.IP "\(bu" 2
| PNC Park | 315
.PP
.PP
20| Citizens Bank Park |
.IP "\(bu" 2
| Yankee Stadium | 80
.IP "\(bu" 2
| Citi Field | 80
.IP "\(bu" 2
| Camden Yards | 90
.IP "\(bu" 2
| Nationals Park | 90
.PP
.PP
21| Coors Field |
.IP "\(bu" 2
| Kauffman Stadium | 560
.IP "\(bu" 2
| Globe Life Park | 650
.IP "\(bu" 2
| Chase Field | 580
.IP "\(bu" 2
| PETCO Park | 830
.PP
.PP
22| Dodger Stadium |
.IP "\(bu" 2
| Angel Stadium | 0
.IP "\(bu" 2
| PETCO Park | 110
.IP "\(bu" 2
| AT&T Park | 340
.IP "\(bu" 2
| O\&.co Coliseum (Oakland) | 340
.IP "\(bu" 2
| Target Field | 1500
.PP
.PP
23| Great America Ball Park |
.IP "\(bu" 2
| Busch Stadium | 310
.IP "\(bu" 2
| Turner Field | 375
.IP "\(bu" 2
| Tropicano Field | 790
.IP "\(bu" 2
| PNC Park | 260
.IP "\(bu" 2
| Progressive Field | 225
.IP "\(bu" 2
| US Cellular Field | 250
.IP "\(bu" 2
| Wrigley Field | 250
.PP
.PP
24| Marlins Park |
.IP "\(bu" 2
| Tropicano Field | 210
.IP "\(bu" 2
| Minute Maid Park | 965
.IP "\(bu" 2
| Fenway Park | 1255
.IP "\(bu" 2
| Nationals Park | 930
.IP "\(bu" 2
| Camden Yards | 930
.IP "\(bu" 2
| Turner Field | 600
.PP
.PP
25| Miller Park |
.IP "\(bu" 2
| Target Field | 300
.IP "\(bu" 2
| Wrigley Field | 80
.IP "\(bu" 2
| US Cellular Field | 80
.IP "\(bu" 2
| Rogers Center | 430
.PP
.PP
26| Nationals Park |
.IP "\(bu" 2
| Camden Yards | 0
.IP "\(bu" 2
| PNC Park | 195
.IP "\(bu" 2
| Turner Field | 560
.IP "\(bu" 2
| Marlins Park | 930
.IP "\(bu" 2
| Citizens Bank Park | 90
.PP
.PP
27|Petco Park |
.IP "\(bu" 2
| Dodger Stadium | 110
.IP "\(bu" 2
| Angel Stadium | 110
.IP "\(bu" 2
| Chase Field | 300
.IP "\(bu" 2
| Coors Field | 830
.PP
.PP
28|PNC Park |
.IP "\(bu" 2
| Progressive Field | 115
.IP "\(bu" 2
| Great American Ballpark | 260
.IP "\(bu" 2
| Camden Yards | 195
.IP "\(bu" 2
| Nationals Park | 195
.IP "\(bu" 2
| Citi Field | 315
.IP "\(bu" 2
| Yankee Stadium | 315
.IP "\(bu" 2
| Rogers Center | 225
.PP
.PP
29|Turner Field |
.IP "\(bu" 2
| Globe Life Park | 740
.IP "\(bu" 2
| Marlins Park | 600
.IP "\(bu" 2
| Camden Yards | 560
.IP "\(bu" 2
| Nationals Park | 560
.IP "\(bu" 2
| Great American Ballpark | 375
.PP
.PP
30| Wrigley Field |
.IP "\(bu" 2
| US Cellular Field | 0
.IP "\(bu" 2
| Miller Park | 80
.IP "\(bu" 2
| Kauffman Stadium | 415
.IP "\(bu" 2
| Comerica Park | 240
.IP "\(bu" 2
| Great America Ballpark | 250
.IP "\(bu" 2
| | 
.PP

