.TH "src/source/plantrip.cpp" 3 "Mon May 16 2016" "Version 1.0" "Baseball Fantasy Vacation Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/source/plantrip.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'header/plantrip\&.h'\fP
.br
\fC#include 'ui_plantrip\&.h'\fP
.br
\fC#include <QDebug>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Baseball Fantasy Vacation Documentation from the source code\&.
