.TH "src/header/purchasewindow.h" 3 "Mon May 16 2016" "Version 1.0" "Baseball Fantasy Vacation Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/header/purchasewindow.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <QWidget>\fP
.br
\fC#include 'database\&.h'\fP
.br
\fC#include 'souvenirtablemodel\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPurchaseWindow\fP"
.br
.ti -1c
.RI "struct \fBPurchaseWindow::purchaseInfo\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBUi\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Baseball Fantasy Vacation Documentation from the source code\&.
