.TH "PurchaseWindow::purchaseInfo" 3 "Mon May 16 2016" "Version 1.0" "Baseball Fantasy Vacation Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PurchaseWindow::purchaseInfo \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <purchasewindow\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "QString \fBstadiumName\fP"
.br
.ti -1c
.RI "QString \fBitemName\fP"
.br
.ti -1c
.RI "double \fBitemPrice\fP"
.br
.ti -1c
.RI "int \fBquantity\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 20 of file purchasewindow\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "QString PurchaseWindow::purchaseInfo::itemName"

.PP
Definition at line 22 of file purchasewindow\&.h\&.
.SS "double PurchaseWindow::purchaseInfo::itemPrice"

.PP
Definition at line 23 of file purchasewindow\&.h\&.
.SS "int PurchaseWindow::purchaseInfo::quantity"

.PP
Definition at line 24 of file purchasewindow\&.h\&.
.SS "QString PurchaseWindow::purchaseInfo::stadiumName"

.PP
Definition at line 21 of file purchasewindow\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Baseball Fantasy Vacation Documentation from the source code\&.
