.TH "src/source/purchasewindow.cpp" 3 "Mon May 16 2016" "Version 1.0" "Baseball Fantasy Vacation Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/source/purchasewindow.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'header/purchasewindow\&.h'\fP
.br
\fC#include 'ui_purchasewindow\&.h'\fP
.br
\fC#include <QSpinBox>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Baseball Fantasy Vacation Documentation from the source code\&.
