.TH "QListData::Data" 3 "Mon May 16 2016" "Version 1.0" "Baseball Fantasy Vacation Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QListData::Data \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <qlist\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "QtPrivate::RefCount \fBref\fP"
.br
.ti -1c
.RI "int \fBalloc\fP"
.br
.ti -1c
.RI "int \fBbegin\fP"
.br
.ti -1c
.RI "int \fBend\fP"
.br
.ti -1c
.RI "void * \fBarray\fP [1]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 82 of file qlist\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "int QListData::Data::alloc"

.PP
Definition at line 84 of file qlist\&.h\&.
.SS "void* QListData::Data::array[1]"

.PP
Definition at line 85 of file qlist\&.h\&.
.SS "int QListData::Data::begin"

.PP
Definition at line 84 of file qlist\&.h\&.
.SS "int QListData::Data::end"

.PP
Definition at line 84 of file qlist\&.h\&.
.SS "QtPrivate::RefCount QListData::Data::ref"

.PP
Definition at line 83 of file qlist\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Baseball Fantasy Vacation Documentation from the source code\&.
