.TH "QListData::NotIndirectLayout" 3 "Mon May 16 2016" "Version 1.0" "Baseball Fantasy Vacation Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QListData::NotIndirectLayout \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <qlist\&.h>\fP
.PP
Inherited by \fBQListData::ArrayCompatibleLayout\fP, and \fBQListData::InlineWithPaddingLayout\fP\&.
.SH "Detailed Description"
.PP 
Definition at line 77 of file qlist\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Baseball Fantasy Vacation Documentation from the source code\&.
