.TH "docs/extra-files/qlist.h" 3 "Mon May 16 2016" "Version 1.0" "Baseball Fantasy Vacation Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
docs/extra-files/qlist.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <QtCore/qalgorithms\&.h>\fP
.br
\fC#include <QtCore/qiterator\&.h>\fP
.br
\fC#include <QtCore/qrefcount\&.h>\fP
.br
\fC#include <QtCore/qarraydata\&.h>\fP
.br
\fC#include <iterator>\fP
.br
\fC#include <list>\fP
.br
\fC#include <algorithm>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <new>\fP
.br
\fC#include <limits\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <QtCore/qbytearraylist\&.h>\fP
.br
\fC#include <QtCore/qstringlist\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBQVector< T >\fP"
.br
.RI "\fIThe \fBQVector\fP class is a template class that provides a dynamic array\&. \fP"
.ti -1c
.RI "class \fBQSet< T >\fP"
.br
.ti -1c
.RI "struct \fBQListSpecialMethods< T >\fP"
.br
.ti -1c
.RI "struct \fBQListData\fP"
.br
.ti -1c
.RI "struct \fBQListData::NotArrayCompatibleLayout\fP"
.br
.ti -1c
.RI "struct \fBQListData::NotIndirectLayout\fP"
.br
.ti -1c
.RI "struct \fBQListData::ArrayCompatibleLayout\fP"
.br
.ti -1c
.RI "struct \fBQListData::InlineWithPaddingLayout\fP"
.br
.ti -1c
.RI "struct \fBQListData::IndirectLayout\fP"
.br
.ti -1c
.RI "struct \fBQListData::Data\fP"
.br
.ti -1c
.RI "class \fBQList< T >\fP"
.br
.RI "\fIThe \fBQList\fP class is a template class that provides lists\&. \fP"
.ti -1c
.RI "struct \fBQList< T >::MemoryLayout\fP"
.br
.ti -1c
.RI "class \fBQList< T >::iterator\fP"
.br
.RI "\fIThe \fBQList::iterator\fP class provides an STL-style non-const iterator for \fBQList\fP and QQueue\&. \fP"
.ti -1c
.RI "class \fBQList< T >::const_iterator\fP"
.br
.RI "\fIThe \fBQList::const_iterator\fP class provides an STL-style const iterator for \fBQList\fP and QQueue\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Baseball Fantasy Vacation Documentation from the source code\&.
