.TH "docs/extra-files/qlist.cpp" 3 "Mon May 16 2016" "Version 1.0" "Baseball Fantasy Vacation Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
docs/extra-files/qlist.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <new>\fP
.br
\fC#include 'qlist\&.h'\fP
.br
\fC#include 'qtools_p\&.h'\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Baseball Fantasy Vacation Documentation from the source code\&.
