.TH "docs/extra-files/qstack.h" 3 "Mon May 16 2016" "Version 1.0" "Baseball Fantasy Vacation Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
docs/extra-files/qstack.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <QtCore/qvector\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBQStack< T >\fP"
.br
.RI "\fIThe \fBQStack\fP class is a template class that provides a stack\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Baseball Fantasy Vacation Documentation from the source code\&.
