.TH "docs/extra-files/qvector.h" 3 "Mon May 16 2016" "Version 1.0" "Baseball Fantasy Vacation Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
docs/extra-files/qvector.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <QtCore/qalgorithms\&.h>\fP
.br
\fC#include <QtCore/qiterator\&.h>\fP
.br
\fC#include <QtCore/qlist\&.h>\fP
.br
\fC#include <QtCore/qrefcount\&.h>\fP
.br
\fC#include <QtCore/qarraydata\&.h>\fP
.br
\fC#include <iterator>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <algorithm>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBQVector< T >\fP"
.br
.RI "\fIThe \fBQVector\fP class is a template class that provides a dynamic array\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Baseball Fantasy Vacation Documentation from the source code\&.
