.TH "src/header/stadiumtablemodel.h" 3 "Mon May 16 2016" "Version 1.0" "Baseball Fantasy Vacation Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/header/stadiumtablemodel.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <QSqlTableModel>\fP
.br
\fC#include <QObject>\fP
.br
\fC#include 'database\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBStadiumTableModel\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Baseball Fantasy Vacation Documentation from the source code\&.
