.TH "Test_Main" 3 "Mon May 16 2016" "Version 1.0" "Baseball Fantasy Vacation Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Test_Main \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits QObject\&.
.SH "Detailed Description"
.PP 
Definition at line 6 of file test_main\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Baseball Fantasy Vacation Documentation from the source code\&.
