.TH "src/header/vertexqueue.h" 3 "Mon May 16 2016" "Version 1.0" "Baseball Fantasy Vacation Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/header/vertexqueue.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'Exceptions\&.h'\fP
.br
\fC#include <QMap>\fP
.br
\fC#include 'vertex\&.h'\fP
.br
\fC#include <QVector>\fP
.br
\fC#include <iostream>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBVertexQueue< C >\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Baseball Fantasy Vacation Documentation from the source code\&.
