.TH "src/header/vertex.h" 3 "Mon May 16 2016" "Version 1.0" "Baseball Fantasy Vacation Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/header/vertex.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <QList>\fP
.br
\fC#include 'Heap\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBEdge\fP"
.br
.ti -1c
.RI "struct \fBcomp\fP"
.br
.RI "\fIThe comp struct Comparator struct used for comparing the weights of two edges\&. \fP"
.ti -1c
.RI "class \fBVertex\fP"
.br
.ti -1c
.RI "struct \fBvertexComp\fP"
.br
.RI "\fIThe \fBvertexComp\fP struct Comparator to be used when inserting vertices into a heap\&. \fP"
.ti -1c
.RI "class \fBVertexSet\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBINF\fP   INT_MAX \- 10000"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define INF   INT_MAX \- 10000"

.PP
Definition at line 4 of file vertex\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Baseball Fantasy Vacation Documentation from the source code\&.
