.TH "vertexComp" 3 "Mon May 16 2016" "Version 1.0" "Baseball Fantasy Vacation Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vertexComp \- The \fBvertexComp\fP struct Comparator to be used when inserting vertices into a heap\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <vertex\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBoperator()\fP (const \fBVertex\fP &v1, const \fBVertex\fP &v2)"
.br
.in -1c
.SH "Detailed Description"
.PP 
The \fBvertexComp\fP struct Comparator to be used when inserting vertices into a heap\&. 
.PP
Definition at line 352 of file vertex\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "bool vertexComp::operator() (const \fBVertex\fP & v1, const \fBVertex\fP & v2)\fC [inline]\fP"

.PP
Definition at line 354 of file vertex\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Baseball Fantasy Vacation Documentation from the source code\&.
